name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
    workflow_dispatch:
      inputs:
        version:
          description: 'Version number (e.g., v1.0.0)'
          required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed orcaslicer_nozzle_variant_maker.py

      - name: Rename artifact
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv dist/orcaslicer_nozzle_variant_maker.exe dist/orcaslicer_nozzle_variant_maker-windows.exe
          elif [ "${{ runner.os }}" == "Linux" ]; then
            mv dist/orcaslicer_nozzle_variant_maker dist/orcaslicer_nozzle_variant_maker-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            mv dist/orcaslicer_nozzle_variant_maker dist/orcaslicer_nozzle_variant_maker-macos
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: dist/orcaslicer_nozzle_variant_maker*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*-build/orcaslicer_nozzle_variant_maker-*
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
